use serde::Deserialize;
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // Tell Cargo to rerun if content changes
    println!("cargo:rerun-if-changed=content/config.toml");
    println!("cargo:rerun-if-changed=content/");

    let config_path = Path::new("content/config.toml");
    let config_str =
        fs::read_to_string(config_path).expect("Failed to read content/config.toml");

    let config: Config = toml::from_str(&config_str).expect("Failed to parse config.toml");

    // Generate Rust code
    let mut code = String::new();
    code.push_str("// AUTO-GENERATED by build.rs - DO NOT EDIT\n\n");
    code.push_str("use crate::graph::vec2;\n\n");
    code.push_str("pub fn populate_graph(graph: &mut Graph) {\n");

    // Generate collection nodes
    for coll in &config.collection {
        let summary_escaped = escape_raw_string(&coll.summary);

        if let Some(parent) = &coll.parent {
            code.push_str(&format!(
                "    graph.add_child_collection(\"{}\", \"{}\", \"{}\", r#\"{}\"#);\n",
                coll.id, parent, coll.title, summary_escaped
            ));
        } else if let Some(p) = &coll.position {
            code.push_str(&format!(
                "    graph.add_collection(\"{}\", vec2({:.1}, {:.1}), \"{}\", r#\"{}\"#);\n",
                coll.id, p.x, p.y, coll.title, summary_escaped
            ));
        } else {
            panic!(
                "Collection '{}' must have either 'position' (for root nodes) or 'parent'",
                coll.id
            );
        }
    }

    code.push_str("\n");

    // Generate post nodes (with embedded markdown)
    for post in &config.post {
        let md_path = format!("content/{}", post.content);
        let md_content =
            fs::read_to_string(&md_path).unwrap_or_else(|_| panic!("Failed to read {}", md_path));

        // Tell cargo to rerun if this specific markdown file changes
        println!("cargo:rerun-if-changed={}", md_path);

        let summary_escaped = escape_raw_string(&post.summary);
        let article_escaped = escape_raw_string(&md_content);

        if let Some(parent) = &post.parent {
            code.push_str(&format!(
                "    graph.add_child_post(\"{}\", \"{}\", \"{}\", r#\"{}\"#, r#\"{}\"#);\n",
                post.id, parent, post.title, summary_escaped, article_escaped
            ));
        } else if let Some(p) = &post.position {
            code.push_str(&format!(
                "    graph.add_post(\"{}\", vec2({:.1}, {:.1}), \"{}\", r#\"{}\"#, r#\"{}\"#);\n",
                post.id, p.x, p.y, post.title, summary_escaped, article_escaped
            ));
        } else {
            panic!(
                "Post '{}' must have either 'position' (for root nodes) or 'parent'",
                post.id
            );
        }

        // Generate tag calls
        for tag in &post.tags {
            code.push_str(&format!(
                "    graph.tag(\"{}\", \"{}\", \"{}\");\n",
                post.id, tag.key, tag.value
            ));
        }
        code.push_str("\n");
    }

    code.push_str("}\n");

    // Write generated code to OUT_DIR
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("content_generated.rs");
    fs::write(&dest_path, code).unwrap();
}

/// Escape content for use in r#"..."# raw strings.
/// The only thing that can break a raw string is the closing delimiter "#
fn escape_raw_string(s: &str) -> String {
    // If the string contains "# we need to use more # symbols
    // For simplicity, we'll just replace "# with something safe
    s.replace("\"#", "\" #")
}

// Config structs for TOML parsing
#[derive(Deserialize)]
struct Config {
    #[serde(default)]
    collection: Vec<CollectionDef>,
    #[serde(default)]
    post: Vec<PostDef>,
}

#[derive(Deserialize)]
struct CollectionDef {
    id: String,
    title: String,
    summary: String,
    position: Option<Position>,
    parent: Option<String>,
}

#[derive(Deserialize)]
struct PostDef {
    id: String,
    title: String,
    summary: String,
    content: String,
    position: Option<Position>,
    parent: Option<String>,
    #[serde(default)]
    tags: Vec<TagDef>,
}

#[derive(Deserialize)]
struct Position {
    x: f64,
    y: f64,
}

#[derive(Deserialize)]
struct TagDef {
    key: String,
    value: String,
}
