[package]
name = "pensieve"
version = "0.1.0"
edition = "2021"
description = "I sometimes find, and I am sure you know the feeling, that I simply have too many thoughts and memories crammed into my mind... One simply siphons the excess thoughts from one's mind, pours them into the basin, and examines them at one's leisure. It becomes easier to spot patterns and links, you understand, when they are in this form."
build = "build.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
pulldown-cmark = "0.9"
console_error_panic_hook = "0.1"

[dependencies.web-sys]
version = "0.3"
features = [
    "Window",
    "Document",
    "Element",
    "HtmlElement",
    "HtmlCanvasElement",
    "CanvasRenderingContext2d",
    "CssStyleDeclaration",
    "DomRect",
    "Event",
    "KeyboardEvent",
    "MouseEvent",
    "WheelEvent",
    "TouchEvent",
    "Touch",
    "TouchList",
    "EventTarget",
    "AddEventListenerOptions",
]

[profile.release]
opt-level = "s"
lto = true

[build-dependencies]
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
